apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-deployment
  labels:
    app: images
spec:
  replicas: 2
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      containers:
        - image: kiran2361993/kubegame:v2
          name: kubegame
          ports:
           - containerPort: 80