apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1  
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
       - image: chaitan28/configmaps:kubegame
         name: configmaps
      imagePullSecrets:              # imagePullSecrets is part of the pod spec, not the container configuration
        - name: docker-pwds
