apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels:
    namespace: development
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "1"                 # 1 CPU cores
        memory: "2Gi"            # 2Gi of memory
