apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  namespace: development
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "1"            # 1 CPU core
        memory: "2Gi"       # 2 GiB of memory
