apiVersion: v1
kind: ResourceQuota
metadata:
    name: count-quota
    labels:
      env: development
spec:
    hard:
      cpu: "5"               # 5 CPU cores
      memory: 10Gi           # 10Gi of memory
      pods: "2"              # 2 pods