apiVersion: v1
kind: ResourceQuota
metadata:
    name: count-quota
    labels:
      namespace: development
spec:
    hard:
      cpu: "5"               # 5 vCPU cores
      memory: 10Gi           # 10Gi of memory
      pods: "10"             # 10 pods