apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv
spec:
  capacity:
    storage: 10Gi                            # Size of the volume
  accessModes:
    - ReadWriteOnce                         # Only one node can write
  persistentVolumeReclaimPolicy: Retain     # Prevents automatic deletion of the EBS volume
  awsElasticBlockStore:
    volumeID: vol-052deecc6dd9f7888          # Replace with your EBS volume ID
    fsType: ext4
