apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testapp
  name: testapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: testapp
    spec:
      containers:
      - image: kiran2361993/kubegame:v1
        name: kubegame
        ports:
         - containerPort: 80