apiVersion: v1
kind: Secret
metadata:
  name: docker-pwd
  labels: 
    name: docker-pwd
type: Opaque
data:
  username: Y2hhaXRhbjI4                                      # base64 encoded username
  password: ZGNrcl9wYXRfTEdZVXpqVXpkYWRsU1E1Y3VrWHhrYnBMWnlZ  # base64 encoded password
