apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    tier: frontend
  ports:
    - protocol: TCP
      port: 6000         # The cluster-wide service port
      targetPort: 80     # The container port on which application is running
     

