apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:                           
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:                       #you can copy the metadata from the ReplicaSet's metadata section to the template's metadata, remove the name 
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80


