apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx1
  namespace: dev
spec:
  containers:
  - image: nginx
    name: nginx

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx2
  namespace: qa
spec:
  containers:
  - image: nginx
    name: nginx

    

