---
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
    selector:
       app.kubernetes.io/name: MyApp

---
apiVersion: v1
kind: Service
metadata:
  name: mydb
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9377
  selector:
      app.kubernetes.io/name: MyApp