apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: dev
type: Opaque
data:
  aws_access_key_id: QUtJQVRGQk1QUExNQUFZN1lPRkE=
  aws_secret_access_key: S0R0V3Ewd0NIRGpiKzlCQnZBZ29DV21XZ1NlMUI0MStEY0FOczB4SQ==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awscli-deployment
  namespace: dev
  labels:
    app: awscli
  annotations:
    description: "Deployment created for awscli"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: awscli
  template:
    metadata:
      labels:
        app: awscli
      annotations:
        description: "Pod created by awscli deployment"
    spec:
      containers:
        - name: awscli-container
          image: kiran2361993/troubleshootingtools:v1
          ports:
            - containerPort: 80
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key
            - name: AWS_REGION
              value: "us-east-1"

